export const errors = {
  string: 'Valor inválido, se esperaba una cadena de caracteres',
  username_required: 'Usuario requerido',
  email_invalid: 'Correo electrónico inválido',
  email_required: 'Correo electrónico requerido',
  password_required: 'Contraseña requerida',
  title_required: 'Título requerido',
  type_required: 'Tipo requerido',
  date_required: 'Fecha requerida',
  description_required: 'Descripción requerida',
  image_required: 'Imagen requerida',
  image_size: 'Imagen muy grande, el tamaño máximo es de 1 MB',
  file_required: 'Archivo requerido',
  file_size: 'Archivo muy grande, el tamaño máximo es de 1 MB',
  password_match: 'Las contraseñas no coinciden',
  name_required: 'Nombre requerido',
  lastname_required: 'Apellido requerido',
  phone_required: 'Teléfono requerido',
  niev_required: 'NIEV requerido',
  curp_required: 'CURP requerido',
  group_required: 'Grupo requerido',
};
